<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <LangVersion>latestmajor</LangVersion>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="RestEase" Version="1.6.4" />
    <PackageReference Include="SFA.DAS.Encoding" Version="1.1.94" />
    <PackageReference Include="SFA.DAS.GovUK.Auth" Version="17.1.199" />
    <PackageReference Include="SFA.DAS.Http" Version="3.2.69" />
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SFA.DAS.EmployerFeedback.Domain\SFA.DAS.EmployerFeedback.Domain.csproj" />
  </ItemGroup>

</Project>
